CREATE TABLE "mytable" (
  "--View 1" text NULL
);

INSERT INTO "mytable" ("--View 1")
VALUES
('CREATE OR REPLACE VIEW WORD_REL (word'),
('SELECT s.word_term'),
('FROM WORD_SYNONYMS s'),
('WHERE a.word_id = s.word_id;'),
(NULL),
('SELECT * FROM WORD_REL;'),
(NULL),
('--View 2'),
('CREATE OR REPLACE VIEW WORD_ANALYSIS (word'),
('SELECT word'),
('FROM WORD_REL;'),
(NULL),
('SELECT * FROM WORD_ANALYSIS;'),
(NULL),
('--View 3'),
('CREATE OR REPLACE VIEW WORD_SUMMARY (word'),
('SELECT word'),
('FROM WORD_REL;'),
(NULL),
('SELECT * FROM WORD_SUMMARY;'),
(NULL),
('--Verify all views'),
('SELECT view_name FROM user_views;'),
('--1'),
('SELECT * FROM WORD_REL;'),
(NULL),
('--2'),
('UPDATE WORD_REL'),
('SET SYN_COL = ''blithe'''),
('WHERE WORD = ''insouciant'';'),
(NULL),
('--3'),
('CREATE OR REPLACE VIEW WORD_REL (word'),
('SELECT s.word_term'),
('FROM WORD_SYNONYMS s'),
('WHERE a.word_id = s.word_id'),
('WITH READ ONLY;'),
(NULL),
('/*'),
('Error at line 3/7: ORA-42399: cannot perform a DML operation on a read-only view'),
(NULL),
(NULL),
('1. UPDATE WORD_REL'),
('2. SET SYN_COL = ''blithe'''),
('3. WHERE WORD = ''insouciant'';'),
('*/'),
(NULL),
('--4'),
('SELECT WORD'),
('FROM WORD_ANALYSIS;'),
(NULL),
('--5'),
('SELECT WORD'),
('FROM (SELECT WORD'),
('FROM WORD_ANALYSIS'),
('ORDER BY WORD_LENGTH DESC)'),
('WHERE ROWNUM <=2;'),
(NULL),
('--6'),
('DROP VIEW WORD_REL;'),
(NULL),
('CREATE OR REPLACE VIEW WORD_REL (word'),
('SELECT s.word_term'),
('FROM WORD_SYNONYMS s'),
('WHERE a.word_id = s.word_id;'),
(NULL),
('--7'),
('SELECT * FROM WORD_SUMMARY;'),
(NULL),
('--8'),
('CREATE OR REPLACE VIEW HOMONYMS_VIEW AS'),
('SELECT WORD_TERM'),
('FROM HOMONYMS;'),
('SELECT * FROM HOMONYMS_VIEW;');
